stages:
  - test
  - build
  - deploy

test:
  stage: test
  image: jitesoft/node-base
  variables:
    NODE_ENV: development
  before_script:
    - npm install --dev
  script:
    - npm run test

build:
  stage: build
  variables:
    NODE_ENV: production
  image: jitesoft/node-base
  before_script:
    - npm install
  script:
    - mkdir package
    - npm run build
    - mv README.md package
    - mv dist package
    - mv src package
    - mv package.templ package/package.json
    - sed -e "s/\${version}/${CI_COMMIT_TAG}/" package/package.json
  artifacts:
    paths: [package]
  only:
   - tags



